/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v14.0
processor: MCXC242
package_id: MCXC242VLH
mcu_data: ksdk2_0
processor_version: 0.16.2
board: FRDM-MCXC242
functionalGroups:
- name: FlexIO_UART_Init
  UUID: 60778229-8c8e-4762-910f-df6836043056
  selectedCore: core0
- name: FlexIO_UART_IRDA_Init
  UUID: e2c6c2f6-8c32-4d64-b8cd-6ef896b0a4cf
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * FlexIO_UART_Init functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'FlexIO_UART_Init'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * FlexIO_UART_Init initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FlexIO_UART_Init'
- type: 'flexio_reg'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'flexio_reg'
- functional_group: 'FlexIO_UART_Init'
- peripheral: 'FLEXIO'
- config_sets:
  - generalConfig:
    - clkConfig:
      - clockSource: 'FlexIoClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - flexioConfig:
      - FLEXEN: 'true'
      - FASTACC: 'false'
      - DBGE: 'true'
      - DOZEN: 'false'
    - tabs:
      - timers_tab:
        - timers:
          - 0:
            - uid: '-1'
            - id: 'TIMER0'
            - number: '0'
            - description: 'TIMER_UART_TX'
            - TIMOD: '1'
            - TSTART: '1'
            - TSTOP: '2'
            - TRGSRC: '1SHIFTER'
            - TRGSEL: '-1'
            - TRGPOL: '1'
            - PINSEL: '5'
            - PINCFG: '0'
            - PINPOL: '0'
            - TIMENA: '2'
            - TIMDIS: '2'
            - TIMRST: '0'
            - TIMOUT: '0'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal8BitLowStr: '34'
            - CMPVal8BitHighStr: '15'
            - TEIE: 'false'
            - params: []
          - 1:
            - uid: '1715158369267'
            - id: 'TIMER1'
            - number: '1'
            - description: 'TIMER_UART_RX'
            - TIMOD: '1'
            - TSTART: '1'
            - TSTOP: '2'
            - TRGSRC: '1PIN'
            - TRGSEL: '4'
            - TRGPOL: '1'
            - PINSEL: '0'
            - PINCFG: '0'
            - PINPOL: '0'
            - TIMENA: '6'
            - TIMDIS: '2'
            - TIMRST: '6'
            - TIMOUT: '2'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal8BitLowStr: '34'
            - CMPVal8BitHighStr: '15'
            - TEIE: 'false'
            - params: []
      - shifters_tab:
        - shifters:
          - 0:
            - uid: '-1'
            - id: 'SHIFTER0'
            - number: '0'
            - description: 'SHFITER_UART_TX'
            - SMOD: '2'
            - SSTART: '2'
            - SSTOP: '3'
            - TIMSEL: '-1'
            - TIMPOL: '0'
            - INSRC: '0'
            - PINSEL: '5'
            - PINCFG: '3'
            - PINPOL: '0'
            - initBufferValTr: 'false'
            - bufferValTr: '0'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
          - 1:
            - uid: '1715159903889'
            - id: 'SHIFTER1'
            - number: '1'
            - description: 'SHFITER_UART_RX'
            - SMOD: '1'
            - SSTART: '2'
            - SSTOP: '3'
            - TIMSEL: '1715158369267'
            - TIMPOL: '1'
            - INSRC: '0'
            - PINSEL: '4'
            - PINCFG: '0'
            - PINPOL: '0'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
      - pins_overview:
        - 0: []
        - 1: []
        - 2: []
        - 3: []
        - 4: []
        - 5: []
        - 6: []
        - 7: []
    - enable_interrupt: 'false'
    - interrupt:
      - IRQn: 'UART2_FLEXIO_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - flexio_params: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void FlexIO_UART_Init_init(void) {
  /* FlexIO initialization */
  /* Control register initialization, set software reset bit then clear it */
  FLEXIO->CTRL |= FLEXIO_CTRL_SWRST_MASK;
  FLEXIO->CTRL &= ~FLEXIO_CTRL_SWRST_MASK;

  /* Write 1 to clear all shifter status */
  FLEXIO->SHIFTSTAT = 0xFFFFFFFFU;

  /* Write 1 to clear all shifter error */
  FLEXIO->SHIFTERR = 0xFFFFFFFFU;

  /* Write 1 to clear all timer status */
  FLEXIO->TIMSTAT = 0xFFFFFFFFU;

#ifdef FLEXIO_TRGSTAT_ETSF_MASK
  /* Write 1 to clear all external trigger status */
  FLEXIO->TRGSTAT = 0xFFFFFFFFU;
#endif /* FLEXIO_TRGSTAT_ETSF_MASK */

#ifdef FLEXIO_PINSTAT_PSF_MASK
  /* Write 1 to clear all pin status */
  FLEXIO->PINSTAT = 0xFFFFFFFFU;
#endif /* FLEXIO_PINSTAT_PSF_MASK */

  /* FlexIO shifter 0 initialization */
  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO_UART_INIT_SHIFTCFG0_INIT
  FLEXIO->SHIFTCFG[0] = FLEXIO_UART_INIT_SHIFTCFG0_INIT;
#else
  FLEXIO->SHIFTCFG[0] = 0x0U;
#endif /* FLEXIO_UART_INIT_SHIFTCFG0_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO_UART_INIT_SHIFTCTL0_INIT
  FLEXIO->SHIFTCTL[0] = FLEXIO_UART_INIT_SHIFTCTL0_INIT;
#else
  FLEXIO->SHIFTCTL[0] = 0x0U;
#endif /* FLEXIO_UART_INIT_SHIFTCTL0_INIT */

  /* Clear the shifter buffer register */
  (void)FLEXIO->SHIFTBUF[0];

  /* FlexIO shifter 1 initialization */
  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO_UART_INIT_SHIFTCFG1_INIT
  FLEXIO->SHIFTCFG[1] = FLEXIO_UART_INIT_SHIFTCFG1_INIT;
#else
  FLEXIO->SHIFTCFG[1] = 0x0U;
#endif /* FLEXIO_UART_INIT_SHIFTCFG1_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO_UART_INIT_SHIFTCTL1_INIT
  FLEXIO->SHIFTCTL[1] = FLEXIO_UART_INIT_SHIFTCTL1_INIT;
#else
  FLEXIO->SHIFTCTL[1] = 0x0U;
#endif /* FLEXIO_UART_INIT_SHIFTCTL1_INIT */

  /* Clear the shifter buffer register */
  (void)FLEXIO->SHIFTBUF[1];

  /* FlexIO timer 0 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO_UART_INIT_TIMCTL0_INIT
  FLEXIO->TIMCTL[0] = FLEXIO_UART_INIT_TIMCTL0_INIT;
#else
  FLEXIO->TIMCTL[0] = 0x0U;
#endif /* FLEXIO_UART_INIT_TIMCTL0_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO_UART_INIT_TIMCFG0_INIT
  FLEXIO->TIMCFG[0] = FLEXIO_UART_INIT_TIMCFG0_INIT;
#else
  FLEXIO->TIMCFG[0] = 0x0U;
#endif /* FLEXIO_UART_INIT_TIMCFG0_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO_UART_INIT_TIMCMP0_INIT
  FLEXIO->TIMCMP[0] = FLEXIO_UART_INIT_TIMCMP0_INIT;
#else
  FLEXIO->TIMCMP[0] = 0x0U;
#endif /* FLEXIO_UART_INIT_TIMCMP0_INIT */

  /* FlexIO timer 1 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO_UART_INIT_TIMCTL1_INIT
  FLEXIO->TIMCTL[1] = FLEXIO_UART_INIT_TIMCTL1_INIT;
#else
  FLEXIO->TIMCTL[1] = 0x0U;
#endif /* FLEXIO_UART_INIT_TIMCTL1_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO_UART_INIT_TIMCFG1_INIT
  FLEXIO->TIMCFG[1] = FLEXIO_UART_INIT_TIMCFG1_INIT;
#else
  FLEXIO->TIMCFG[1] = 0x0U;
#endif /* FLEXIO_UART_INIT_TIMCFG1_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO_UART_INIT_TIMCMP1_INIT
  FLEXIO->TIMCMP[1] = FLEXIO_UART_INIT_TIMCMP1_INIT;
#else
  FLEXIO->TIMCMP[1] = 0x0U;
#endif /* FLEXIO_UART_INIT_TIMCMP1_INIT */

  /* Shifter status interrupt register initialization */
#ifdef FLEXIO_UART_INIT_SHIFTSIEN_INIT
  FLEXIO->SHIFTSIEN = FLEXIO_UART_INIT_SHIFTSIEN_INIT;
#else
  FLEXIO->SHIFTSIEN = 0x0U;
#endif /* FLEXIO_UART_INIT_SHIFTSIEN_INIT */

  /* Shifter error interrupt register initialization */
#ifdef FLEXIO_UART_INIT_SHIFTEIEN_INIT
  FLEXIO->SHIFTEIEN = FLEXIO_UART_INIT_SHIFTEIEN_INIT;
#else
  FLEXIO->SHIFTEIEN = 0x0U;
#endif /* FLEXIO_UART_INIT_SHIFTEIEN_INIT */

  /* Timer interrupt register initialization */
#ifdef FLEXIO_UART_INIT_TIMIEN_INIT
  FLEXIO->TIMIEN = FLEXIO_UART_INIT_TIMIEN_INIT;
#else
  FLEXIO->TIMIEN = 0x0U;
#endif /* FLEXIO_UART_INIT_TIMIEN_INIT */

  /* Shifter status DMA register initialization */
#ifdef FLEXIO_UART_INIT_SHIFTSDEN_INIT
  FLEXIO->SHIFTSDEN = FLEXIO_UART_INIT_SHIFTSDEN_INIT;
#else
  FLEXIO->SHIFTSDEN = 0x0U;
#endif /* FLEXIO_UART_INIT_SHIFTSDEN_INIT */

#ifdef FLEXIO_TIMERSDEN_TSDE_MASK
  /* Timer status DMA register initialization */
#ifdef FLEXIO_UART_INIT_TIMERSDEN_INIT
  FLEXIO->TIMERSDEN = FLEXIO_UART_INIT_TIMERSDEN_INIT;
#else
  FLEXIO->TIMERSDEN = 0x0U;
#endif /* FLEXIO_UART_INIT_TIMERSDEN_INIT */
#endif /* FLEXIO_TIMERSDEN_TSDE_MASK */

#ifdef FLEXIO_SHIFTSTATE_STATE_MASK
  /* Shifter state register initialization */
#ifdef FLEXIO_UART_INIT_SHIFTSTATE_INIT
  FLEXIO->SHIFTSTATE = FLEXIO_UART_INIT_SHIFTSTATE_INIT;
#else
  FLEXIO->SHIFTSTATE = 0x0U;
#endif /* FLEXIO_UART_INIT_SHIFTSTATE_INIT */
#endif /* FLEXIO_SHIFTSTATE_STATE_MASK */

#ifdef FLEXIO_TRIGIEN_TRIE_MASK
  /* Trigger interrupt enable register initialization */
#ifdef FLEXIO_UART_INIT_TRIGIEN_INIT
  FLEXIO->TRIGIEN = FLEXIO_UART_INIT_TRIGIEN_INIT;
#else
  FLEXIO->TRIGIEN = 0x0U;
#endif /* FLEXIO_UART_INIT_TRIGIEN_INIT */
#endif /* FLEXIO_TRIGIEN_TRIE_MASK */

#ifdef FLEXIO_PINIEN_PSIE_MASK
  /* Pin interrupt enable register */
#ifdef FLEXIO_UART_INIT_PINIEN_INIT
  FLEXIO->PINIEN = FLEXIO_UART_INIT_PINIEN_INIT;
#else
  FLEXIO->PINIEN = 0x0U;
#endif /* FLEXIO_UART_INIT_PINIEN_INIT */
#endif /* FLEXIO_PINIEN_PSIE_MASK */

#ifdef FLEXIO_PINREN_PRE_MASK
  /* Pin rising edge enable register initialization */
#ifdef FLEXIO_UART_INIT_PINREN_INIT
  FLEXIO->PINREN = FLEXIO_UART_INIT_PINREN_INIT;
#else
  FLEXIO->PINREN = 0x0U;
#endif /* FLEXIO_UART_INIT_PINREN_INIT */
#endif /* FLEXIO_PINREN_PRE_MASK */

#ifdef FLEXIO_PINFEN_PFE_MASK
  /* Pin falling edge enable register initialization */
#ifdef FLEXIO_UART_INIT_PINFEN_INIT
  FLEXIO->PINFEN = FLEXIO_UART_INIT_PINFEN_INIT;
#else
  FLEXIO->PINFEN = 0x0U;
#endif /* FLEXIO_UART_INIT_PINFEN_INIT */
#endif /* FLEXIO_PINFEN_PFE_MASK */

#ifdef FLEXIO_PINOUTE_OUTE_MASK
  /* Pin output enable register initialization */
#ifdef FLEXIO_UART_INIT_PINOUTE_INIT
  FLEXIO->PINOUTE = FLEXIO_UART_INIT_PINOUTE_INIT;
#else
  FLEXIO->PINOUTE = 0x0U;
#endif /* FLEXIO_UART_INIT_PINOUTE_INIT */
#endif /* FLEXIO_PINOUTE_OUTE_MASK */

#ifdef FLEXIO_PINOUTD_OUTD_MASK
  /* Pin output register initialization */
#ifdef FLEXIO_UART_INIT_PINOUTD_INIT
  FLEXIO->PINOUTD = FLEXIO_UART_INIT_PINOUTD_INIT;
#else
  FLEXIO->PINOUTD = 0x0U;
#endif /* FLEXIO_UART_INIT_PINOUTD_INIT */
#endif /* FLEXIO_PINOUTD_OUTD_MASK */

#ifdef FLEXIO_UART_INIT_CTRL_INIT
  FLEXIO->CTRL = (FLEXIO_UART_INIT_CTRL_INIT & ~FLEXIO_CTRL_SWRST_MASK);
#else
  FLEXIO->CTRL = 0x0U;
#endif /* FLEXIO_UART_INIT_CTRL_INIT */
}

/***********************************************************************************************************************
 * FlexIO_UART_IRDA_Init functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC_2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC_2'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'FlexIO_UART_IRDA_Init'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_2_init(void) {
} */

/***********************************************************************************************************************
 * FlexIO_UART_IRDA_Init initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FlexIO_UART_IRDA_Init'
- type: 'flexio_reg'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'flexio_reg'
- functional_group: 'FlexIO_UART_IRDA_Init'
- peripheral: 'FLEXIO'
- config_sets:
  - generalConfig:
    - clkConfig:
      - clockSource: 'FlexIoClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - flexioConfig:
      - FLEXEN: 'true'
      - FASTACC: 'false'
      - DBGE: 'true'
      - DOZEN: 'false'
    - tabs:
      - timers_tab:
        - timers:
          - 0:
            - uid: '-1'
            - id: 'TIMER0'
            - number: '0'
            - description: 'TIMER_UART_TX'
            - TIMOD: '1'
            - TSTART: '1'
            - TSTOP: '2'
            - TRGSRC: '1SHIFTER'
            - TRGSEL: '-1'
            - TRGPOL: '1'
            - PINSEL: '5'
            - PINCFG: '0'
            - PINPOL: '0'
            - TIMENA: '2'
            - TIMDIS: '2'
            - TIMRST: '0'
            - TIMOUT: '0'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal8BitLowStr: '34'
            - CMPVal8BitHighStr: '15'
            - TEIE: 'false'
            - params: []
          - 1:
            - uid: '1715158369267'
            - id: 'TIMER1'
            - number: '1'
            - description: 'TIMER_UART_RX'
            - TIMOD: '1'
            - TSTART: '1'
            - TSTOP: '2'
            - TRGSRC: '1PIN'
            - TRGSEL: '4'
            - TRGPOL: '1'
            - PINSEL: '0'
            - PINCFG: '0'
            - PINPOL: '0'
            - TIMENA: '6'
            - TIMDIS: '2'
            - TIMRST: '6'
            - TIMOUT: '2'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal8BitLowStr: '34'
            - CMPVal8BitHighStr: '15'
            - TEIE: 'false'
            - params: []
          - 2:
            - uid: '1715166421735'
            - id: 'TIMER2'
            - number: '2'
            - description: 'TIMER_UART_IRDA_Encode'
            - TIMOD: '2'
            - TSTART: '0'
            - TSTOP: '0'
            - TRGSRC: '1PIN'
            - TRGSEL: '5'
            - TRGPOL: '1'
            - PINSEL: '1'
            - PINCFG: '3'
            - PINPOL: '0'
            - TIMENA: '6'
            - TIMDIS: '6'
            - TIMRST: '0'
            - TIMOUT: '0'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal8BitLowStr: '12'
            - CMPVal8BitHighStr: '56'
            - TEIE: 'false'
            - params: []
          - 3:
            - uid: '1715166462306'
            - id: 'TIMER3'
            - number: '3'
            - description: 'TIMER_UART_IRDA_Decode'
            - TIMOD: '3'
            - TSTART: '0'
            - TSTOP: '0'
            - TRGSRC: '1PIN'
            - TRGSEL: '3'
            - TRGPOL: '0'
            - PINSEL: '4'
            - PINCFG: '3'
            - PINPOL: '1'
            - TIMENA: '6'
            - TIMDIS: '2'
            - TIMRST: '6'
            - TIMOUT: '2'
            - TIMDEC: '0'
            - timerClockFreqCustomStr: ''
            - CMPVal16BitStr: '69'
            - TEIE: 'false'
            - params: []
      - shifters_tab:
        - shifters:
          - 0:
            - uid: '-1'
            - id: 'SHIFTER0'
            - number: '0'
            - description: 'SHFITER_UART_TX'
            - SMOD: '2'
            - SSTART: '2'
            - SSTOP: '3'
            - TIMSEL: '-1'
            - TIMPOL: '0'
            - INSRC: '0'
            - PINSEL: '5'
            - PINCFG: '3'
            - PINPOL: '0'
            - initBufferValTr: 'false'
            - bufferValTr: '0'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
          - 1:
            - uid: '1715159903889'
            - id: 'SHIFTER1'
            - number: '1'
            - description: 'SHFITER_UART_RX'
            - SMOD: '1'
            - SSTART: '2'
            - SSTOP: '3'
            - TIMSEL: '1715158369267'
            - TIMPOL: '1'
            - INSRC: '0'
            - PINSEL: '4'
            - PINCFG: '0'
            - PINPOL: '0'
            - SSIE: 'false'
            - SEIE: 'false'
            - SSDE: 'false'
            - params: []
      - pins_overview:
        - 0: []
        - 1: []
        - 2: []
        - 3: []
        - 4: []
        - 5: []
        - 6: []
        - 7: []
    - enable_interrupt: 'false'
    - interrupt:
      - IRQn: 'UART2_FLEXIO_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - flexio_params: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void FlexIO_UART_IRDA_Init_init(void) {
  /* FlexIO initialization */
  /* Control register initialization, set software reset bit then clear it */
  FLEXIO->CTRL |= FLEXIO_CTRL_SWRST_MASK;
  FLEXIO->CTRL &= ~FLEXIO_CTRL_SWRST_MASK;

  /* Write 1 to clear all shifter status */
  FLEXIO->SHIFTSTAT = 0xFFFFFFFFU;

  /* Write 1 to clear all shifter error */
  FLEXIO->SHIFTERR = 0xFFFFFFFFU;

  /* Write 1 to clear all timer status */
  FLEXIO->TIMSTAT = 0xFFFFFFFFU;

#ifdef FLEXIO_TRGSTAT_ETSF_MASK
  /* Write 1 to clear all external trigger status */
  FLEXIO->TRGSTAT = 0xFFFFFFFFU;
#endif /* FLEXIO_TRGSTAT_ETSF_MASK */

#ifdef FLEXIO_PINSTAT_PSF_MASK
  /* Write 1 to clear all pin status */
  FLEXIO->PINSTAT = 0xFFFFFFFFU;
#endif /* FLEXIO_PINSTAT_PSF_MASK */

  /* FlexIO shifter 0 initialization */
  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_SHIFTCFG0_INIT
  FLEXIO->SHIFTCFG[0] = FLEXIO_UART_IRDA_INIT_SHIFTCFG0_INIT;
#else
  FLEXIO->SHIFTCFG[0] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_SHIFTCFG0_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_SHIFTCTL0_INIT
  FLEXIO->SHIFTCTL[0] = FLEXIO_UART_IRDA_INIT_SHIFTCTL0_INIT;
#else
  FLEXIO->SHIFTCTL[0] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_SHIFTCTL0_INIT */

  /* Clear the shifter buffer register */
  (void)FLEXIO->SHIFTBUF[0];

  /* FlexIO shifter 1 initialization */
  /* Shifter configuration register SHIFTCFGn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_SHIFTCFG1_INIT
  FLEXIO->SHIFTCFG[1] = FLEXIO_UART_IRDA_INIT_SHIFTCFG1_INIT;
#else
  FLEXIO->SHIFTCFG[1] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_SHIFTCFG1_INIT */
  
  /* Shifter control register SHIFTCTLn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_SHIFTCTL1_INIT
  FLEXIO->SHIFTCTL[1] = FLEXIO_UART_IRDA_INIT_SHIFTCTL1_INIT;
#else
  FLEXIO->SHIFTCTL[1] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_SHIFTCTL1_INIT */

  /* Clear the shifter buffer register */
  (void)FLEXIO->SHIFTBUF[1];

  /* FlexIO timer 0 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCTL0_INIT
  FLEXIO->TIMCTL[0] = FLEXIO_UART_IRDA_INIT_TIMCTL0_INIT;
#else
  FLEXIO->TIMCTL[0] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCTL0_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCFG0_INIT
  FLEXIO->TIMCFG[0] = FLEXIO_UART_IRDA_INIT_TIMCFG0_INIT;
#else
  FLEXIO->TIMCFG[0] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCFG0_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCMP0_INIT
  FLEXIO->TIMCMP[0] = FLEXIO_UART_IRDA_INIT_TIMCMP0_INIT;
#else
  FLEXIO->TIMCMP[0] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCMP0_INIT */

  /* FlexIO timer 1 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCTL1_INIT
  FLEXIO->TIMCTL[1] = FLEXIO_UART_IRDA_INIT_TIMCTL1_INIT;
#else
  FLEXIO->TIMCTL[1] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCTL1_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCFG1_INIT
  FLEXIO->TIMCFG[1] = FLEXIO_UART_IRDA_INIT_TIMCFG1_INIT;
#else
  FLEXIO->TIMCFG[1] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCFG1_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCMP1_INIT
  FLEXIO->TIMCMP[1] = FLEXIO_UART_IRDA_INIT_TIMCMP1_INIT;
#else
  FLEXIO->TIMCMP[1] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCMP1_INIT */

  /* FlexIO timer 2 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCTL2_INIT
  FLEXIO->TIMCTL[2] = FLEXIO_UART_IRDA_INIT_TIMCTL2_INIT;
#else
  FLEXIO->TIMCTL[2] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCTL2_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCFG2_INIT
  FLEXIO->TIMCFG[2] = FLEXIO_UART_IRDA_INIT_TIMCFG2_INIT;
#else
  FLEXIO->TIMCFG[2] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCFG2_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCMP2_INIT
  FLEXIO->TIMCMP[2] = FLEXIO_UART_IRDA_INIT_TIMCMP2_INIT;
#else
  FLEXIO->TIMCMP[2] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCMP2_INIT */

  /* FlexIO timer 3 initialization */
  /* Timer control register configuration register TIMCTLn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCTL3_INIT
  FLEXIO->TIMCTL[3] = FLEXIO_UART_IRDA_INIT_TIMCTL3_INIT;
#else
  FLEXIO->TIMCTL[3] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCTL3_INIT */

  /* Timer configuration register TIMCFGn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCFG3_INIT
  FLEXIO->TIMCFG[3] = FLEXIO_UART_IRDA_INIT_TIMCFG3_INIT;
#else
  FLEXIO->TIMCFG[3] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCFG3_INIT */

  /* Timer compare register TIMCMPn initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMCMP3_INIT
  FLEXIO->TIMCMP[3] = FLEXIO_UART_IRDA_INIT_TIMCMP3_INIT;
#else
  FLEXIO->TIMCMP[3] = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMCMP3_INIT */

  /* Shifter status interrupt register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_SHIFTSIEN_INIT
  FLEXIO->SHIFTSIEN = FLEXIO_UART_IRDA_INIT_SHIFTSIEN_INIT;
#else
  FLEXIO->SHIFTSIEN = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_SHIFTSIEN_INIT */

  /* Shifter error interrupt register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_SHIFTEIEN_INIT
  FLEXIO->SHIFTEIEN = FLEXIO_UART_IRDA_INIT_SHIFTEIEN_INIT;
#else
  FLEXIO->SHIFTEIEN = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_SHIFTEIEN_INIT */

  /* Timer interrupt register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMIEN_INIT
  FLEXIO->TIMIEN = FLEXIO_UART_IRDA_INIT_TIMIEN_INIT;
#else
  FLEXIO->TIMIEN = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMIEN_INIT */

  /* Shifter status DMA register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_SHIFTSDEN_INIT
  FLEXIO->SHIFTSDEN = FLEXIO_UART_IRDA_INIT_SHIFTSDEN_INIT;
#else
  FLEXIO->SHIFTSDEN = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_SHIFTSDEN_INIT */

#ifdef FLEXIO_TIMERSDEN_TSDE_MASK
  /* Timer status DMA register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TIMERSDEN_INIT
  FLEXIO->TIMERSDEN = FLEXIO_UART_IRDA_INIT_TIMERSDEN_INIT;
#else
  FLEXIO->TIMERSDEN = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TIMERSDEN_INIT */
#endif /* FLEXIO_TIMERSDEN_TSDE_MASK */

#ifdef FLEXIO_SHIFTSTATE_STATE_MASK
  /* Shifter state register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_SHIFTSTATE_INIT
  FLEXIO->SHIFTSTATE = FLEXIO_UART_IRDA_INIT_SHIFTSTATE_INIT;
#else
  FLEXIO->SHIFTSTATE = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_SHIFTSTATE_INIT */
#endif /* FLEXIO_SHIFTSTATE_STATE_MASK */

#ifdef FLEXIO_TRIGIEN_TRIE_MASK
  /* Trigger interrupt enable register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_TRIGIEN_INIT
  FLEXIO->TRIGIEN = FLEXIO_UART_IRDA_INIT_TRIGIEN_INIT;
#else
  FLEXIO->TRIGIEN = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_TRIGIEN_INIT */
#endif /* FLEXIO_TRIGIEN_TRIE_MASK */

#ifdef FLEXIO_PINIEN_PSIE_MASK
  /* Pin interrupt enable register */
#ifdef FLEXIO_UART_IRDA_INIT_PINIEN_INIT
  FLEXIO->PINIEN = FLEXIO_UART_IRDA_INIT_PINIEN_INIT;
#else
  FLEXIO->PINIEN = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_PINIEN_INIT */
#endif /* FLEXIO_PINIEN_PSIE_MASK */

#ifdef FLEXIO_PINREN_PRE_MASK
  /* Pin rising edge enable register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_PINREN_INIT
  FLEXIO->PINREN = FLEXIO_UART_IRDA_INIT_PINREN_INIT;
#else
  FLEXIO->PINREN = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_PINREN_INIT */
#endif /* FLEXIO_PINREN_PRE_MASK */

#ifdef FLEXIO_PINFEN_PFE_MASK
  /* Pin falling edge enable register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_PINFEN_INIT
  FLEXIO->PINFEN = FLEXIO_UART_IRDA_INIT_PINFEN_INIT;
#else
  FLEXIO->PINFEN = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_PINFEN_INIT */
#endif /* FLEXIO_PINFEN_PFE_MASK */

#ifdef FLEXIO_PINOUTE_OUTE_MASK
  /* Pin output enable register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_PINOUTE_INIT
  FLEXIO->PINOUTE = FLEXIO_UART_IRDA_INIT_PINOUTE_INIT;
#else
  FLEXIO->PINOUTE = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_PINOUTE_INIT */
#endif /* FLEXIO_PINOUTE_OUTE_MASK */

#ifdef FLEXIO_PINOUTD_OUTD_MASK
  /* Pin output register initialization */
#ifdef FLEXIO_UART_IRDA_INIT_PINOUTD_INIT
  FLEXIO->PINOUTD = FLEXIO_UART_IRDA_INIT_PINOUTD_INIT;
#else
  FLEXIO->PINOUTD = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_PINOUTD_INIT */
#endif /* FLEXIO_PINOUTD_OUTD_MASK */

#ifdef FLEXIO_UART_IRDA_INIT_CTRL_INIT
  FLEXIO->CTRL = (FLEXIO_UART_IRDA_INIT_CTRL_INIT & ~FLEXIO_CTRL_SWRST_MASK);
#else
  FLEXIO->CTRL = 0x0U;
#endif /* FLEXIO_UART_IRDA_INIT_CTRL_INIT */
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void FlexIO_UART_Init_CommonPreInit(void)
{
  /* Enable clock gate of the FLEXIO peripheral. */
  SIM->SCGC5 |= SIM_SCGC5_FLEXIO_MASK;
}

void FlexIO_UART_Init(void)
{
  /* Common pre-initialization */
  FlexIO_UART_Init_CommonPreInit();
  /* Initialize components */
  FlexIO_UART_Init_init();
}

static void FlexIO_UART_IRDA_Init_CommonPreInit(void)
{
  /* Enable clock gate of the FLEXIO peripheral. */
  SIM->SCGC5 |= SIM_SCGC5_FLEXIO_MASK;
}

void FlexIO_UART_IRDA_Init(void)
{
  /* Common pre-initialization */
  FlexIO_UART_IRDA_Init_CommonPreInit();
  /* Initialize components */
  FlexIO_UART_IRDA_Init_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
}
