/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTD4 (number 61), J1[9]
  @{ */

/* Symbols to be used with PORT driver */
#define FLEXIO_UART_INITPINS_UART_TX_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define FLEXIO_UART_INITPINS_UART_TX_PIN 4U                   /*!<@brief PORT pin number */
#define FLEXIO_UART_INITPINS_UART_TX_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTD5 (number 62), J1[11]/J3[2]/SDA_PTD5
  @{ */

/* Symbols to be used with PORT driver */
#define FLEXIO_UART_INITPINS_UART_RX_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define FLEXIO_UART_INITPINS_UART_RX_PIN 5U                   /*!<@brief PORT pin number */
#define FLEXIO_UART_INITPINS_UART_RX_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void FlexIO_UART_InitPins(void);

/*! @name PORTD3 (number 60), J1[7]
  @{ */

/* Symbols to be used with PORT driver */
#define FLEXIO_UART_IRDA_INITPINS_IRDA_RX_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define FLEXIO_UART_IRDA_INITPINS_IRDA_RX_PIN 3U                   /*!<@brief PORT pin number */
#define FLEXIO_UART_IRDA_INITPINS_IRDA_RX_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORTD5 (number 62), J1[11]/J3[2]/SDA_PTD5
  @{ */

/* Symbols to be used with PORT driver */
#define FLEXIO_UART_IRDA_INITPINS_UART_RX_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define FLEXIO_UART_IRDA_INITPINS_UART_RX_PIN 5U                   /*!<@brief PORT pin number */
#define FLEXIO_UART_IRDA_INITPINS_UART_RX_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name PORTD4 (number 61), J1[9]
  @{ */

/* Symbols to be used with PORT driver */
#define FLEXIO_UART_IRDA_INITPINS_UART_TX_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define FLEXIO_UART_IRDA_INITPINS_UART_TX_PIN 4U                   /*!<@brief PORT pin number */
#define FLEXIO_UART_IRDA_INITPINS_UART_TX_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void FlexIO_UART_IRDA_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
